<?php

$projectRoot = dirname(__DIR__);
$gatewayDir = $projectRoot . DIRECTORY_SEPARATOR . 'services' . DIRECTORY_SEPARATOR . 'whatsapp-web-gateway';

return [
    'default_instance' => 'lab01',
    'default_daily_limit' => (int)env('WHATSAPP_ALT_DEFAULT_DAILY_LIMIT', 250),
    'rotation_window_hours' => (int)env('WHATSAPP_ALT_ROTATION_WINDOW_HOURS', 24),
    'per_number_window_hours' => (float)env('WHATSAPP_ALT_PER_NUMBER_WINDOW_HOURS', 0.1667), // ~10 minutos
    'per_number_limit' => (int)env('WHATSAPP_ALT_PER_NUMBER_LIMIT', 5),
    'per_campaign_window_hours' => (float)env('WHATSAPP_ALT_PER_CAMPAIGN_WINDOW_HOURS', 24),
    'per_campaign_limit' => (int)env('WHATSAPP_ALT_PER_CAMPAIGN_LIMIT', 1),
    'instances' => [
        'lab01' => [
            'label' => 'Gateway laboratorio 01',
            'description' => 'Numero de testes principal. Ajuste as variaveis .env antes de iniciar.',
            'base_url' => env('WHATSAPP_ALT_GATEWAY_URL', 'http://127.0.0.1:4010') ?: 'http://127.0.0.1:4010',
            'start_command' => $gatewayDir . DIRECTORY_SEPARATOR . 'start-gateway.bat',
            'command_token' => env('WHATSAPP_ALT_GATEWAY_COMMAND_TOKEN', 'alterar-token-envio') ?: 'alterar-token-envio',
            'webhook_token' => env('WHATSAPP_ALT_GATEWAY_WEBHOOK_TOKEN', 'alterar-token-webhook'),
            'default_line_label' => 'WhatsApp Web alternativo',
            'session_hint' => 'crm-sandbox',
            'daily_limit' => (int)env('WHATSAPP_ALT_GATEWAY_LAB01_DAILY_LIMIT', 250),
            'enabled' => true,
        ],
        'lab02' => [
            'label' => 'Gateway laboratorio 02',
            'description' => 'Instancia isolada para o segundo numero de testes (porta 4020).',
            'base_url' => env('WHATSAPP_ALT_GATEWAY_LAB02_URL', 'http://127.0.0.1:4020'),
            'start_command' => $gatewayDir . DIRECTORY_SEPARATOR . 'start-gateway-lab02.bat',
            'command_token' => env('WHATSAPP_ALT_GATEWAY_LAB02_COMMAND_TOKEN', 'alterar-token-envio-lab02'),
            'webhook_token' => env('WHATSAPP_ALT_GATEWAY_LAB02_WEBHOOK_TOKEN', 'alterar-token-webhook-lab02'),
            'default_line_label' => 'WhatsApp Web alternativo 02',
            'session_hint' => 'crm-sandbox-02',
            'daily_limit' => (int)env('WHATSAPP_ALT_GATEWAY_LAB02_DAILY_LIMIT', 250),
            'enabled' => true,
        ],
        'lab03' => [
            'label' => 'Gateway laboratorio 03',
            'description' => 'Instancia isolada para o terceiro numero de testes (porta 4030).',
            'base_url' => env('WHATSAPP_ALT_GATEWAY_LAB03_URL', 'http://127.0.0.1:4030'),
            'start_command' => $gatewayDir . DIRECTORY_SEPARATOR . 'start-gateway-lab03.bat',
            'command_token' => env('WHATSAPP_ALT_GATEWAY_LAB03_COMMAND_TOKEN', ''),
            'webhook_token' => env('WHATSAPP_ALT_GATEWAY_LAB03_WEBHOOK_TOKEN', ''),
            'default_line_label' => 'WhatsApp Web alternativo 03',
            'session_hint' => 'crm-sandbox-03',
            'daily_limit' => (int)env('WHATSAPP_ALT_GATEWAY_LAB03_DAILY_LIMIT', 250),
            'enabled' => true,
        ],
        'lab04' => [
            'label' => 'Gateway laboratorio 04',
            'description' => 'Instancia isolada para o quarto numero de testes (porta 4040).',
            'base_url' => env('WHATSAPP_ALT_GATEWAY_LAB04_URL', 'http://127.0.0.1:4040'),
            'start_command' => $gatewayDir . DIRECTORY_SEPARATOR . 'start-gateway-lab04.bat',
            'command_token' => env('WHATSAPP_ALT_GATEWAY_LAB04_COMMAND_TOKEN', ''),
            'webhook_token' => env('WHATSAPP_ALT_GATEWAY_LAB04_WEBHOOK_TOKEN', ''),
            'default_line_label' => 'WhatsApp Web alternativo 04',
            'session_hint' => 'crm-sandbox-04',
            'daily_limit' => (int)env('WHATSAPP_ALT_GATEWAY_LAB04_DAILY_LIMIT', 250),
            'enabled' => true,
        ],
        'lab05' => [
            'label' => 'Gateway laboratorio 05',
            'description' => 'Instancia isolada para o quinto numero de testes (porta 4050).',
            'base_url' => env('WHATSAPP_ALT_GATEWAY_LAB05_URL', 'http://127.0.0.1:4050'),
            'start_command' => $gatewayDir . DIRECTORY_SEPARATOR . 'start-gateway-lab05.bat',
            'command_token' => env('WHATSAPP_ALT_GATEWAY_LAB05_COMMAND_TOKEN', ''),
            'webhook_token' => env('WHATSAPP_ALT_GATEWAY_LAB05_WEBHOOK_TOKEN', ''),
            'default_line_label' => 'WhatsApp Web alternativo 05',
            'session_hint' => 'crm-sandbox-05',
            'daily_limit' => (int)env('WHATSAPP_ALT_GATEWAY_LAB05_DAILY_LIMIT', 250),
            'enabled' => true,
        ],
        'lab06' => [
            'label' => 'Gateway laboratorio 06',
            'description' => 'Instancia isolada para o sexto numero de testes (porta 4060).',
            'base_url' => env('WHATSAPP_ALT_GATEWAY_LAB06_URL', 'http://127.0.0.1:4060'),
            'start_command' => $gatewayDir . DIRECTORY_SEPARATOR . 'start-gateway-lab06.bat',
            'command_token' => env('WHATSAPP_ALT_GATEWAY_LAB06_COMMAND_TOKEN', ''),
            'webhook_token' => env('WHATSAPP_ALT_GATEWAY_LAB06_WEBHOOK_TOKEN', ''),
            'default_line_label' => 'WhatsApp Web alternativo 06',
            'session_hint' => 'crm-sandbox-06',
            'daily_limit' => (int)env('WHATSAPP_ALT_GATEWAY_LAB06_DAILY_LIMIT', 250),
            'enabled' => true,
        ],
        'lab07' => [
            'label' => 'Gateway laboratorio 07',
            'description' => 'Instancia isolada para o setimo numero de testes (porta 4070).',
            'base_url' => env('WHATSAPP_ALT_GATEWAY_LAB07_URL', 'http://127.0.0.1:4070'),
            'start_command' => $gatewayDir . DIRECTORY_SEPARATOR . 'start-gateway-lab07.bat',
            'command_token' => env('WHATSAPP_ALT_GATEWAY_LAB07_COMMAND_TOKEN', ''),
            'webhook_token' => env('WHATSAPP_ALT_GATEWAY_LAB07_WEBHOOK_TOKEN', ''),
            'default_line_label' => 'WhatsApp Web alternativo 07',
            'session_hint' => 'crm-sandbox-07',
            'daily_limit' => (int)env('WHATSAPP_ALT_GATEWAY_LAB07_DAILY_LIMIT', 250),
            'enabled' => true,
        ],
        'lab08' => [
            'label' => 'Gateway laboratorio 08',
            'description' => 'Instancia isolada para o oitavo numero de testes (porta 4080).',
            'base_url' => env('WHATSAPP_ALT_GATEWAY_LAB08_URL', 'http://127.0.0.1:4080'),
            'start_command' => $gatewayDir . DIRECTORY_SEPARATOR . 'start-gateway-lab08.bat',
            'command_token' => env('WHATSAPP_ALT_GATEWAY_LAB08_COMMAND_TOKEN', ''),
            'webhook_token' => env('WHATSAPP_ALT_GATEWAY_LAB08_WEBHOOK_TOKEN', ''),
            'default_line_label' => 'WhatsApp Web alternativo 08',
            'session_hint' => 'crm-sandbox-08',
            'daily_limit' => (int)env('WHATSAPP_ALT_GATEWAY_LAB08_DAILY_LIMIT', 250),
            'enabled' => true,
        ],
        'lab09' => [
            'label' => 'Gateway laboratorio 09',
            'description' => 'Instancia isolada para o nono numero de testes (porta 4090).',
            'base_url' => env('WHATSAPP_ALT_GATEWAY_LAB09_URL', 'http://127.0.0.1:4090'),
            'start_command' => $gatewayDir . DIRECTORY_SEPARATOR . 'start-gateway-lab09.bat',
            'command_token' => env('WHATSAPP_ALT_GATEWAY_LAB09_COMMAND_TOKEN', ''),
            'webhook_token' => env('WHATSAPP_ALT_GATEWAY_LAB09_WEBHOOK_TOKEN', ''),
            'default_line_label' => 'WhatsApp Web alternativo 09',
            'session_hint' => 'crm-sandbox-09',
            'daily_limit' => (int)env('WHATSAPP_ALT_GATEWAY_LAB09_DAILY_LIMIT', 250),
            'enabled' => true,
        ],
        'wpp01' => [
            'label' => 'Gateway WPPConnect 01',
            'description' => 'Canal alternativo 2 (QR) com payload completo (wa_id, profile, foto).',
            'base_url' => env('WHATSAPP_ALT_GATEWAY_WPP01_URL', 'http://192.168.1.137:4100'),
            'start_command' => $gatewayDir . DIRECTORY_SEPARATOR . 'start-gateway-wpp01.bat',
            'command_token' => env('WHATSAPP_ALT_GATEWAY_WPP01_COMMAND_TOKEN', 'alterar-token-envio-wpp01'),
            'webhook_token' => env('WHATSAPP_ALT_GATEWAY_WPP01_WEBHOOK_TOKEN', 'alterar-token-webhook-wpp01'),
            'default_line_label' => 'WhatsApp Web alternativo WPP 01',
            'session_hint' => 'wppconnect',
            'daily_limit' => (int)env('WHATSAPP_ALT_GATEWAY_WPP01_DAILY_LIMIT', 250),
            'enabled' => true,
        ],
        'lab00' => [
            'label' => 'Gateway laboratorio 00',
            'description' => 'Instancia adicional de testes (porta 4000).',
            'base_url' => env('WHATSAPP_ALT_GATEWAY_LAB00_URL', 'http://127.0.0.1:4000'),
            'start_command' => $gatewayDir . DIRECTORY_SEPARATOR . 'start-gateway-lab00.bat',
            'command_token' => env('WHATSAPP_ALT_GATEWAY_LAB00_COMMAND_TOKEN', ''),
            'webhook_token' => env('WHATSAPP_ALT_GATEWAY_LAB00_WEBHOOK_TOKEN', ''),
            'default_line_label' => 'WhatsApp Web alternativo 00',
            'session_hint' => 'crm-sandbox-00',
            'daily_limit' => (int)env('WHATSAPP_ALT_GATEWAY_LAB00_DAILY_LIMIT', 250),
            'enabled' => true,
        ],
    ],
];
